spring.application.name=mysiedler-client
logging.file.name=logs/mysiedler-client.log

siedler.client.server-base-url=http://localhost:8080
siedler.client.web-socket-url=ws://localhost:8080/ws
siedler.client.player-name=Player
